# TCL File Generated by Component Editor 22.1
# Sat Aug 03 20:34:55 PDT 2024
# DO NOT MODIFY


# 
# gpu "gpu" v1.0
#  2024.08.03.20:34:55
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module gpu
# 
set_module_property DESCRIPTION ""
set_module_property NAME gpu
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME gpu
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL gpu
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file gpu.sv SYSTEM_VERILOG PATH rtl/gpu.sv TOP_LEVEL_FILE
add_fileset_file gpu_core.sv SYSTEM_VERILOG PATH rtl/gpu_core.sv
add_fileset_file rop.sv SYSTEM_VERILOG PATH rtl/vertex_processor/rop.sv
add_fileset_file vertex_processor.sv SYSTEM_VERILOG PATH rtl/vertex_processor/vertex_processor.sv
add_fileset_file vn_shader.sv SYSTEM_VERILOG PATH rtl/vertex_processor/vn_shader.sv
add_fileset_file depth.sv SYSTEM_VERILOG PATH rtl/raster/depth.sv
add_fileset_file raster.sv SYSTEM_VERILOG PATH rtl/raster/raster.sv
add_fileset_file timer.sv SYSTEM_VERILOG PATH rtl/vertex_processor/timer.sv
add_fileset_file avlmm.sv SYSTEM_VERILOG PATH rtl/avalon_front_end/avlmm.sv
add_fileset_file avlmm_control.sv SYSTEM_VERILOG PATH rtl/avalon_front_end/avlmm_control.sv
add_fileset_file avlmm_dma.sv SYSTEM_VERILOG PATH rtl/avalon_front_end/avlmm_dma.sv
add_fileset_file madd.v VERILOG PATH ip/madd/madd.v
add_fileset_file madd_0002.v VERILOG PATH ip/madd/madd/madd_0002.v
add_fileset_file div.v VERILOG PATH ip/div/div.v
add_fileset_file div_32x32.v VERILOG PATH ip/div_32x32/div_32x32.v
add_fileset_file fifo_108x32.v VERILOG PATH ip/fifo_108x32/fifo_108x32.v
add_fileset_file fifo_27x32.v VERILOG PATH ip/fifo_27x32/fifo_27x32.v
add_fileset_file fifo_32x32.v VERILOG PATH ip/fifo_32x32/fifo_32x32.v
add_fileset_file ram.v VERILOG PATH ip/ram/ram.v
add_fileset_file ram_17x17.v VERILOG PATH ip/ram_17x17/ram_17x17.v
add_fileset_file fifo_1x20.v VERILOG PATH ip/fifo_1x20/fifo_1x20.v
add_fileset_file vga_adapter.sv SYSTEM_VERILOG PATH rtl/vga-core/vga_adapter.sv
add_fileset_file vga_address_translator.sv SYSTEM_VERILOG PATH rtl/vga-core/vga_address_translator.sv
add_fileset_file vga_controller.sv SYSTEM_VERILOG PATH rtl/vga-core/vga_controller.sv
add_fileset_file vga_pll.sv SYSTEM_VERILOG PATH rtl/vga-core/vga_pll.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL gpu
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file gpu.sv SYSTEM_VERILOG PATH rtl/gpu.sv
add_fileset_file gpu_core.sv SYSTEM_VERILOG PATH rtl/gpu_core.sv
add_fileset_file rop.sv SYSTEM_VERILOG PATH rtl/vertex_processor/rop.sv
add_fileset_file vertex_processor.sv SYSTEM_VERILOG PATH rtl/vertex_processor/vertex_processor.sv
add_fileset_file vn_shader.sv SYSTEM_VERILOG PATH rtl/vertex_processor/vn_shader.sv
add_fileset_file depth.sv SYSTEM_VERILOG PATH rtl/raster/depth.sv
add_fileset_file raster.sv SYSTEM_VERILOG PATH rtl/raster/raster.sv
add_fileset_file timer.sv SYSTEM_VERILOG PATH rtl/vertex_processor/timer.sv
add_fileset_file avlmm.sv SYSTEM_VERILOG PATH rtl/avalon_front_end/avlmm.sv
add_fileset_file avlmm_control.sv SYSTEM_VERILOG PATH rtl/avalon_front_end/avlmm_control.sv
add_fileset_file avlmm_dma.sv SYSTEM_VERILOG PATH rtl/avalon_front_end/avlmm_dma.sv
add_fileset_file madd.v VERILOG PATH ip/madd/madd.v
add_fileset_file madd_0002.v VERILOG PATH ip/madd/madd/madd_0002.v
add_fileset_file div.v VERILOG PATH ip/div/div.v
add_fileset_file div_32x32.v VERILOG PATH ip/div_32x32/div_32x32.v
add_fileset_file fifo_108x32.v VERILOG PATH ip/fifo_108x32/fifo_108x32.v
add_fileset_file fifo_27x32.v VERILOG PATH ip/fifo_27x32/fifo_27x32.v
add_fileset_file fifo_32x32.v VERILOG PATH ip/fifo_32x32/fifo_32x32.v
add_fileset_file ram.v VERILOG PATH ip/ram/ram.v
add_fileset_file ram_17x17.v VERILOG PATH ip/ram_17x17/ram_17x17.v
add_fileset_file fifo_1x20.v VERILOG PATH ip/fifo_1x20/fifo_1x20.v
add_fileset_file vga_adapter.sv SYSTEM_VERILOG PATH rtl/vga-core/vga_adapter.sv
add_fileset_file vga_address_translator.sv SYSTEM_VERILOG PATH rtl/vga-core/vga_address_translator.sv
add_fileset_file vga_controller.sv SYSTEM_VERILOG PATH rtl/vga-core/vga_controller.sv
add_fileset_file vga_pll.sv SYSTEM_VERILOG PATH rtl/vga-core/vga_pll.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges BOTH
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avlmm_ctrl_slave
# 
add_interface avlmm_ctrl_slave avalon end
set_interface_property avlmm_ctrl_slave addressUnits SYMBOLS
set_interface_property avlmm_ctrl_slave associatedClock clock
set_interface_property avlmm_ctrl_slave associatedReset reset
set_interface_property avlmm_ctrl_slave bitsPerSymbol 8
set_interface_property avlmm_ctrl_slave burstOnBurstBoundariesOnly false
set_interface_property avlmm_ctrl_slave burstcountUnits WORDS
set_interface_property avlmm_ctrl_slave explicitAddressSpan 0
set_interface_property avlmm_ctrl_slave holdTime 0
set_interface_property avlmm_ctrl_slave linewrapBursts false
set_interface_property avlmm_ctrl_slave maximumPendingReadTransactions 0
set_interface_property avlmm_ctrl_slave maximumPendingWriteTransactions 0
set_interface_property avlmm_ctrl_slave readLatency 0
set_interface_property avlmm_ctrl_slave readWaitTime 1
set_interface_property avlmm_ctrl_slave setupTime 0
set_interface_property avlmm_ctrl_slave timingUnits Cycles
set_interface_property avlmm_ctrl_slave writeWaitTime 0
set_interface_property avlmm_ctrl_slave ENABLED true
set_interface_property avlmm_ctrl_slave EXPORT_OF ""
set_interface_property avlmm_ctrl_slave PORT_NAME_MAP ""
set_interface_property avlmm_ctrl_slave CMSIS_SVD_VARIABLES ""
set_interface_property avlmm_ctrl_slave SVD_ADDRESS_GROUP ""

add_interface_port avlmm_ctrl_slave slave_address address Input 4
add_interface_port avlmm_ctrl_slave slave_writedata writedata Input 32
add_interface_port avlmm_ctrl_slave slave_write write Input 1
add_interface_port avlmm_ctrl_slave slave_read read Input 1
add_interface_port avlmm_ctrl_slave slave_byteenable byteenable Input 4
add_interface_port avlmm_ctrl_slave slave_readdata readdata Output 32
add_interface_port avlmm_ctrl_slave slave_waitrequest waitrequest Output 1
set_interface_assignment avlmm_ctrl_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avlmm_ctrl_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avlmm_ctrl_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avlmm_ctrl_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avlmm_dma_master
# 
add_interface avlmm_dma_master avalon start
set_interface_property avlmm_dma_master addressUnits SYMBOLS
set_interface_property avlmm_dma_master associatedClock clock
set_interface_property avlmm_dma_master associatedReset reset
set_interface_property avlmm_dma_master bitsPerSymbol 8
set_interface_property avlmm_dma_master burstOnBurstBoundariesOnly false
set_interface_property avlmm_dma_master burstcountUnits WORDS
set_interface_property avlmm_dma_master doStreamReads false
set_interface_property avlmm_dma_master doStreamWrites false
set_interface_property avlmm_dma_master holdTime 0
set_interface_property avlmm_dma_master linewrapBursts false
set_interface_property avlmm_dma_master maximumPendingReadTransactions 0
set_interface_property avlmm_dma_master maximumPendingWriteTransactions 0
set_interface_property avlmm_dma_master readLatency 0
set_interface_property avlmm_dma_master readWaitTime 1
set_interface_property avlmm_dma_master setupTime 0
set_interface_property avlmm_dma_master timingUnits Cycles
set_interface_property avlmm_dma_master writeWaitTime 0
set_interface_property avlmm_dma_master ENABLED true
set_interface_property avlmm_dma_master EXPORT_OF ""
set_interface_property avlmm_dma_master PORT_NAME_MAP ""
set_interface_property avlmm_dma_master CMSIS_SVD_VARIABLES ""
set_interface_property avlmm_dma_master SVD_ADDRESS_GROUP ""

add_interface_port avlmm_dma_master master_readdata readdata Input 32
add_interface_port avlmm_dma_master master_waitrequest waitrequest Input 1
add_interface_port avlmm_dma_master master_address address Output 32
add_interface_port avlmm_dma_master master_read read Output 1
add_interface_port avlmm_dma_master master_byteenable byteenable Output 4


# 
# connection point vga_conduit
# 
add_interface vga_conduit conduit end
set_interface_property vga_conduit associatedClock clock
set_interface_property vga_conduit associatedReset ""
set_interface_property vga_conduit ENABLED true
set_interface_property vga_conduit EXPORT_OF ""
set_interface_property vga_conduit PORT_NAME_MAP ""
set_interface_property vga_conduit CMSIS_SVD_VARIABLES ""
set_interface_property vga_conduit SVD_ADDRESS_GROUP ""

add_interface_port vga_conduit VGA_B vga_b Output 8
add_interface_port vga_conduit VGA_BLANK_N vga_blank_n Output 1
add_interface_port vga_conduit VGA_CLK vga_clk Output 1
add_interface_port vga_conduit VGA_G vga_g Output 8
add_interface_port vga_conduit VGA_HS vga_hs Output 1
add_interface_port vga_conduit VGA_R vga_r Output 8
add_interface_port vga_conduit VGA_SYNC_N vga_sync_n Output 1
add_interface_port vga_conduit VGA_VS vga_vs Output 1

