# TCL File Generated by Component Editor 22.1
# Fri May 02 18:39:34 PDT 2025
# DO NOT MODIFY


# 
# gpu_axil "gpu_axil" v1.0
#  2025.05.02.18:39:34
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module gpu_axil
# 
set_module_property DESCRIPTION ""
set_module_property NAME gpu_axil
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME gpu_axil
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL gpu
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file gpu.sv SYSTEM_VERILOG PATH rtl/gpu.sv TOP_LEVEL_FILE
add_fileset_file gpu_core.sv SYSTEM_VERILOG PATH rtl/gpu_core.sv
add_fileset_file rop.sv SYSTEM_VERILOG PATH rtl/vertex_processor/rop.sv
add_fileset_file vertex_processor.sv SYSTEM_VERILOG PATH rtl/vertex_processor/vertex_processor.sv
add_fileset_file vn_shader.sv SYSTEM_VERILOG PATH rtl/vertex_processor/vn_shader.sv
add_fileset_file depth.sv SYSTEM_VERILOG PATH rtl/raster/depth.sv
add_fileset_file raster.sv SYSTEM_VERILOG PATH rtl/raster/raster.sv
add_fileset_file timer.sv SYSTEM_VERILOG PATH rtl/vertex_processor/timer.sv
add_fileset_file madd.v VERILOG PATH ip/madd/madd.v
add_fileset_file madd_0002.v VERILOG PATH ip/madd/madd/madd_0002.v
add_fileset_file div.v VERILOG PATH ip/div/div.v
add_fileset_file div_32x32.v VERILOG PATH ip/div_32x32/div_32x32.v
add_fileset_file fifo_108x32.v VERILOG PATH ip/fifo_108x32/fifo_108x32.v
add_fileset_file fifo_27x32.v VERILOG PATH ip/fifo_27x32/fifo_27x32.v
add_fileset_file fifo_32x32.v VERILOG PATH ip/fifo_32x32/fifo_32x32.v
add_fileset_file ram.v VERILOG PATH ip/ram/ram.v
add_fileset_file ram_17x17.v VERILOG PATH ip/ram_17x17/ram_17x17.v
add_fileset_file fifo_1x20.v VERILOG PATH ip/fifo_1x20/fifo_1x20.v
add_fileset_file vga_adapter.sv SYSTEM_VERILOG PATH rtl/vga-core/vga_adapter.sv
add_fileset_file vga_address_translator.sv SYSTEM_VERILOG PATH rtl/vga-core/vga_address_translator.sv
add_fileset_file vga_controller.sv SYSTEM_VERILOG PATH rtl/vga-core/vga_controller.sv
add_fileset_file vga_pll.sv SYSTEM_VERILOG PATH rtl/vga-core/vga_pll.sv
add_fileset_file axil.sv SYSTEM_VERILOG PATH rtl/axil_front_end/axil.sv
add_fileset_file axil_control.sv SYSTEM_VERILOG PATH rtl/axil_front_end/axil_control.sv
add_fileset_file axil_dma.sv SYSTEM_VERILOG PATH rtl/axil_front_end/axil_dma.sv
add_fileset_file wbm2axilite.v VERILOG PATH submodules/wb2axip/rtl/wbm2axilite.v
add_fileset_file axilrd2wbsp.v VERILOG PATH submodules/wb2axip/rtl/axilrd2wbsp.v
add_fileset_file axilwr2wbsp.v VERILOG PATH submodules/wb2axip/rtl/axilwr2wbsp.v
add_fileset_file axlite2wbsp.v VERILOG PATH submodules/wb2axip/rtl/axlite2wbsp.v
add_fileset_file wbarbiter.v VERILOG PATH submodules/wb2axip/rtl/wbarbiter.v
add_fileset_file axil_rop_backend.sv SYSTEM_VERILOG PATH rtl/axil_rop_backend.sv
add_fileset_file async_fifo.v VERILOG PATH submodules/async_fifo/rtl/async_fifo.v
add_fileset_file fifomem.v VERILOG PATH submodules/async_fifo/rtl/fifomem.v
add_fileset_file fifomem_dp.v VERILOG PATH submodules/async_fifo/rtl/fifomem_dp.v
add_fileset_file rptr_empty.v VERILOG PATH submodules/async_fifo/rtl/rptr_empty.v
add_fileset_file sync_ptr.v VERILOG PATH submodules/async_fifo/rtl/sync_ptr.v
add_fileset_file sync_r2w.v VERILOG PATH submodules/async_fifo/rtl/sync_r2w.v
add_fileset_file sync_w2r.v VERILOG PATH submodules/async_fifo/rtl/sync_w2r.v
add_fileset_file wptr_full.v VERILOG PATH submodules/async_fifo/rtl/wptr_full.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL gpu
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file gpu.sv SYSTEM_VERILOG PATH rtl/gpu.sv
add_fileset_file gpu_core.sv SYSTEM_VERILOG PATH rtl/gpu_core.sv
add_fileset_file rop.sv SYSTEM_VERILOG PATH rtl/vertex_processor/rop.sv
add_fileset_file vertex_processor.sv SYSTEM_VERILOG PATH rtl/vertex_processor/vertex_processor.sv
add_fileset_file vn_shader.sv SYSTEM_VERILOG PATH rtl/vertex_processor/vn_shader.sv
add_fileset_file depth.sv SYSTEM_VERILOG PATH rtl/raster/depth.sv
add_fileset_file raster.sv SYSTEM_VERILOG PATH rtl/raster/raster.sv
add_fileset_file timer.sv SYSTEM_VERILOG PATH rtl/vertex_processor/timer.sv
add_fileset_file avlmm.sv SYSTEM_VERILOG PATH rtl/avalon_front_end/avlmm.sv
add_fileset_file avlmm_control.sv SYSTEM_VERILOG PATH rtl/avalon_front_end/avlmm_control.sv
add_fileset_file avlmm_dma.sv SYSTEM_VERILOG PATH rtl/avalon_front_end/avlmm_dma.sv
add_fileset_file madd.v VERILOG PATH ip/madd/madd.v
add_fileset_file madd_0002.v VERILOG PATH ip/madd/madd/madd_0002.v
add_fileset_file div.v VERILOG PATH ip/div/div.v
add_fileset_file div_32x32.v VERILOG PATH ip/div_32x32/div_32x32.v
add_fileset_file fifo_108x32.v VERILOG PATH ip/fifo_108x32/fifo_108x32.v
add_fileset_file fifo_27x32.v VERILOG PATH ip/fifo_27x32/fifo_27x32.v
add_fileset_file fifo_32x32.v VERILOG PATH ip/fifo_32x32/fifo_32x32.v
add_fileset_file ram.v VERILOG PATH ip/ram/ram.v
add_fileset_file ram_17x17.v VERILOG PATH ip/ram_17x17/ram_17x17.v
add_fileset_file fifo_1x20.v VERILOG PATH ip/fifo_1x20/fifo_1x20.v
add_fileset_file vga_adapter.sv SYSTEM_VERILOG PATH rtl/vga-core/vga_adapter.sv
add_fileset_file vga_address_translator.sv SYSTEM_VERILOG PATH rtl/vga-core/vga_address_translator.sv
add_fileset_file vga_controller.sv SYSTEM_VERILOG PATH rtl/vga-core/vga_controller.sv
add_fileset_file vga_pll.sv SYSTEM_VERILOG PATH rtl/vga-core/vga_pll.sv
add_fileset_file axil.sv SYSTEM_VERILOG PATH rtl/axil_front_end/axil.sv
add_fileset_file axil_control.sv SYSTEM_VERILOG PATH rtl/axil_front_end/axil_control.sv
add_fileset_file axil_dma.sv SYSTEM_VERILOG PATH rtl/axil_front_end/axil_dma.sv
add_fileset_file wbm2axilite.v VERILOG PATH submodules/wb2axip/rtl/wbm2axilite.v
add_fileset_file axilrd2wbsp.v VERILOG PATH submodules/wb2axip/rtl/axilrd2wbsp.v
add_fileset_file axilwr2wbsp.v VERILOG PATH submodules/wb2axip/rtl/axilwr2wbsp.v
add_fileset_file axlite2wbsp.v VERILOG PATH submodules/wb2axip/rtl/axlite2wbsp.v
add_fileset_file wbarbiter.v VERILOG PATH submodules/wb2axip/rtl/wbarbiter.v
add_fileset_file axil_rop_backend.sv SYSTEM_VERILOG PATH rtl/axil_rop_backend.sv
add_fileset_file async_fifo.v VERILOG PATH submodules/async_fifo/rtl/async_fifo.v
add_fileset_file fifomem.v VERILOG PATH submodules/async_fifo/rtl/fifomem.v
add_fileset_file fifomem_dp.v VERILOG PATH submodules/async_fifo/rtl/fifomem_dp.v
add_fileset_file rptr_empty.v VERILOG PATH submodules/async_fifo/rtl/rptr_empty.v
add_fileset_file sync_ptr.v VERILOG PATH submodules/async_fifo/rtl/sync_ptr.v
add_fileset_file sync_r2w.v VERILOG PATH submodules/async_fifo/rtl/sync_r2w.v
add_fileset_file sync_w2r.v VERILOG PATH submodules/async_fifo/rtl/sync_w2r.v
add_fileset_file wptr_full.v VERILOG PATH submodules/async_fifo/rtl/wptr_full.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges BOTH
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq_gpu irq Output 1


# 
# connection point axi4lite_mstr_dma
# 
add_interface axi4lite_mstr_dma axi4lite start
set_interface_property axi4lite_mstr_dma associatedClock clock
set_interface_property axi4lite_mstr_dma associatedReset reset
set_interface_property axi4lite_mstr_dma readIssuingCapability 1
set_interface_property axi4lite_mstr_dma writeIssuingCapability 1
set_interface_property axi4lite_mstr_dma combinedIssuingCapability 1
set_interface_property axi4lite_mstr_dma ENABLED true
set_interface_property axi4lite_mstr_dma EXPORT_OF ""
set_interface_property axi4lite_mstr_dma PORT_NAME_MAP ""
set_interface_property axi4lite_mstr_dma CMSIS_SVD_VARIABLES ""
set_interface_property axi4lite_mstr_dma SVD_ADDRESS_GROUP ""

add_interface_port axi4lite_mstr_dma mstr_axi_awvalid_o awvalid Output 1
add_interface_port axi4lite_mstr_dma mstr_axi_awready_i awready Input 1
add_interface_port axi4lite_mstr_dma mstr_axi_awaddr_o awaddr Output 32
add_interface_port axi4lite_mstr_dma mstr_axi_awprot_o awprot Output 3
add_interface_port axi4lite_mstr_dma mstr_axi_wvalid_o wvalid Output 1
add_interface_port axi4lite_mstr_dma mstr_axi_wready_i wready Input 1
add_interface_port axi4lite_mstr_dma mstr_axi_wdata_o wdata Output 32
add_interface_port axi4lite_mstr_dma mstr_axi_wstrb_o wstrb Output 4
add_interface_port axi4lite_mstr_dma mstr_axi_bvalid_i bvalid Input 1
add_interface_port axi4lite_mstr_dma mstr_axi_bresp_i bresp Input 2
add_interface_port axi4lite_mstr_dma mstr_axi_bready_o bready Output 1
add_interface_port axi4lite_mstr_dma mstr_axi_arvalid_o arvalid Output 1
add_interface_port axi4lite_mstr_dma mstr_axi_arready_i arready Input 1
add_interface_port axi4lite_mstr_dma mstr_axi_araddr_o araddr Output 32
add_interface_port axi4lite_mstr_dma mstr_axi_arprot_o arprot Output 3
add_interface_port axi4lite_mstr_dma mstr_axi_rvalid_i rvalid Input 1
add_interface_port axi4lite_mstr_dma mstr_axi_rready_o rready Output 1
add_interface_port axi4lite_mstr_dma mstr_axi_rdata_i rdata Input 32
add_interface_port axi4lite_mstr_dma mstr_axi_rresp_i rresp Input 2


# 
# connection point axi4lite_mstr_rop
# 
add_interface axi4lite_mstr_rop axi4lite start
set_interface_property axi4lite_mstr_rop associatedClock clock
set_interface_property axi4lite_mstr_rop associatedReset reset
set_interface_property axi4lite_mstr_rop readIssuingCapability 1
set_interface_property axi4lite_mstr_rop writeIssuingCapability 1
set_interface_property axi4lite_mstr_rop combinedIssuingCapability 1
set_interface_property axi4lite_mstr_rop ENABLED true
set_interface_property axi4lite_mstr_rop EXPORT_OF ""
set_interface_property axi4lite_mstr_rop PORT_NAME_MAP ""
set_interface_property axi4lite_mstr_rop CMSIS_SVD_VARIABLES ""
set_interface_property axi4lite_mstr_rop SVD_ADDRESS_GROUP ""

add_interface_port axi4lite_mstr_rop rop_axi_awvalid_o awvalid Output 1
add_interface_port axi4lite_mstr_rop rop_axi_awready_i awready Input 1
add_interface_port axi4lite_mstr_rop rop_axi_awaddr_o awaddr Output 32
add_interface_port axi4lite_mstr_rop rop_axi_awprot_o awprot Output 3
add_interface_port axi4lite_mstr_rop rop_axi_wvalid_o wvalid Output 1
add_interface_port axi4lite_mstr_rop rop_axi_wready_i wready Input 1
add_interface_port axi4lite_mstr_rop rop_axi_wdata_o wdata Output 32
add_interface_port axi4lite_mstr_rop rop_axi_wstrb_o wstrb Output 4
add_interface_port axi4lite_mstr_rop rop_axi_bvalid_i bvalid Input 1
add_interface_port axi4lite_mstr_rop rop_axi_bresp_i bresp Input 2
add_interface_port axi4lite_mstr_rop rop_axi_bready_o bready Output 1
add_interface_port axi4lite_mstr_rop rop_axi_arvalid_o arvalid Output 1
add_interface_port axi4lite_mstr_rop rop_axi_arready_i arready Input 1
add_interface_port axi4lite_mstr_rop rop_axi_araddr_o araddr Output 32
add_interface_port axi4lite_mstr_rop rop_axi_arprot_o arprot Output 3
add_interface_port axi4lite_mstr_rop rop_axi_rvalid_i rvalid Input 1
add_interface_port axi4lite_mstr_rop rop_axi_rready_o rready Output 1
add_interface_port axi4lite_mstr_rop rop_axi_rdata_i rdata Input 32
add_interface_port axi4lite_mstr_rop rop_axi_rresp_i rresp Input 2


# 
# connection point axi4lite_slve_ctrl
# 
add_interface axi4lite_slve_ctrl axi4lite end
set_interface_property axi4lite_slve_ctrl associatedClock clock
set_interface_property axi4lite_slve_ctrl associatedReset reset
set_interface_property axi4lite_slve_ctrl readAcceptanceCapability 1
set_interface_property axi4lite_slve_ctrl writeAcceptanceCapability 1
set_interface_property axi4lite_slve_ctrl combinedAcceptanceCapability 1
set_interface_property axi4lite_slve_ctrl readDataReorderingDepth 1
set_interface_property axi4lite_slve_ctrl bridgesToMaster ""
set_interface_property axi4lite_slve_ctrl ENABLED true
set_interface_property axi4lite_slve_ctrl EXPORT_OF ""
set_interface_property axi4lite_slve_ctrl PORT_NAME_MAP ""
set_interface_property axi4lite_slve_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property axi4lite_slve_ctrl SVD_ADDRESS_GROUP ""

add_interface_port axi4lite_slve_ctrl ctrl_axi_awvalid_i awvalid Input 1
add_interface_port axi4lite_slve_ctrl ctrl_axi_awready_o awready Output 1
add_interface_port axi4lite_slve_ctrl ctrl_axi_awaddr_i awaddr Input 8
add_interface_port axi4lite_slve_ctrl ctrl_axi_awprot_i awprot Input 3
add_interface_port axi4lite_slve_ctrl ctrl_axi_wvalid_i wvalid Input 1
add_interface_port axi4lite_slve_ctrl ctrl_axi_wready_o wready Output 1
add_interface_port axi4lite_slve_ctrl ctrl_axi_wdata_i wdata Input 32
add_interface_port axi4lite_slve_ctrl ctrl_axi_wstrb_i wstrb Input 4
add_interface_port axi4lite_slve_ctrl ctrl_axi_bvalid_o bvalid Output 1
add_interface_port axi4lite_slve_ctrl ctrl_axi_bresp_o bresp Output 2
add_interface_port axi4lite_slve_ctrl ctrl_axi_bready_i bready Input 1
add_interface_port axi4lite_slve_ctrl ctrl_axi_arvalid_i arvalid Input 1
add_interface_port axi4lite_slve_ctrl ctrl_axi_arready_o arready Output 1
add_interface_port axi4lite_slve_ctrl ctrl_axi_araddr_i araddr Input 8
add_interface_port axi4lite_slve_ctrl ctrl_axi_arprot_i arprot Input 3
add_interface_port axi4lite_slve_ctrl ctrl_axi_rvalid_o rvalid Output 1
add_interface_port axi4lite_slve_ctrl ctrl_axi_rready_i rready Input 1
add_interface_port axi4lite_slve_ctrl ctrl_axi_rdata_o rdata Output 32
add_interface_port axi4lite_slve_ctrl ctrl_axi_rresp_o rresp Output 2

