// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef GPU_REGS_H
#define GPU_REGS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <linux/types.h>

// Reg - gpu_ctrl::GPU_CTRL
#define GPU_CTRL__GPU_CTRL__GPU_START_bm 0x1
#define GPU_CTRL__GPU_CTRL__GPU_START_bp 0
#define GPU_CTRL__GPU_CTRL__GPU_START_bw 1
#define GPU_CTRL__GPU_CTRL__GPU_START_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t GPU_START :1;
        uint32_t :31;
    } f;
    uint32_t w;
} gpu_ctrl__GPU_CTRL_t;

// Reg - gpu_ctrl::GPU_INTR_STATUS
#define GPU_CTRL__GPU_INTR_STATUS__GPU_DONE_STAT_bm 0x1
#define GPU_CTRL__GPU_INTR_STATUS__GPU_DONE_STAT_bp 0
#define GPU_CTRL__GPU_INTR_STATUS__GPU_DONE_STAT_bw 1
#define GPU_CTRL__GPU_INTR_STATUS__GPU_DONE_STAT_reset 0x0
#define GPU_CTRL__GPU_INTR_STATUS__UNUSED_bm 0xfffffffe
#define GPU_CTRL__GPU_INTR_STATUS__UNUSED_bp 1
#define GPU_CTRL__GPU_INTR_STATUS__UNUSED_bw 31
#define GPU_CTRL__GPU_INTR_STATUS__UNUSED_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t GPU_DONE_STAT :1;
        uint32_t UNUSED :31;
    } f;
    uint32_t w;
} gpu_ctrl__GPU_INTR_STATUS_t;

// Reg - gpu_ctrl::GPU_INTR_CLEAR
#define GPU_CTRL__GPU_INTR_CLEAR__GPU_DONE_CLR_bm 0x1
#define GPU_CTRL__GPU_INTR_CLEAR__GPU_DONE_CLR_bp 0
#define GPU_CTRL__GPU_INTR_CLEAR__GPU_DONE_CLR_bw 1
#define GPU_CTRL__GPU_INTR_CLEAR__GPU_DONE_CLR_reset 0x0
#define GPU_CTRL__GPU_INTR_CLEAR__UNUSED_bm 0xfffffffe
#define GPU_CTRL__GPU_INTR_CLEAR__UNUSED_bp 1
#define GPU_CTRL__GPU_INTR_CLEAR__UNUSED_bw 31
#define GPU_CTRL__GPU_INTR_CLEAR__UNUSED_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t GPU_DONE_CLR :1;
        uint32_t UNUSED :31;
    } f;
    uint32_t w;
} gpu_ctrl__GPU_INTR_CLEAR_t;

// Reg - gpu_ctrl::GPU_FE_MEM_OFFSET
#define GPU_CTRL__GPU_FE_MEM_OFFSET__MEM_OFFSET_bm 0xffffffff
#define GPU_CTRL__GPU_FE_MEM_OFFSET__MEM_OFFSET_bp 0
#define GPU_CTRL__GPU_FE_MEM_OFFSET__MEM_OFFSET_bw 32
#define GPU_CTRL__GPU_FE_MEM_OFFSET__MEM_OFFSET_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t MEM_OFFSET :32;
    } f;
    uint32_t w;
} gpu_ctrl__GPU_FE_MEM_OFFSET_t;

// Reg - gpu_ctrl::GPU_BE_MEM_OFFSET
#define GPU_CTRL__GPU_BE_MEM_OFFSET__MEM_OFFSET_bm 0xffffffff
#define GPU_CTRL__GPU_BE_MEM_OFFSET__MEM_OFFSET_bp 0
#define GPU_CTRL__GPU_BE_MEM_OFFSET__MEM_OFFSET_bw 32
#define GPU_CTRL__GPU_BE_MEM_OFFSET__MEM_OFFSET_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t MEM_OFFSET :32;
    } f;
    uint32_t w;
} gpu_ctrl__GPU_BE_MEM_OFFSET_t;

// Addrmap - gpu_ctrl
typedef struct __attribute__ ((__packed__)) {
    gpu_ctrl__GPU_CTRL_t GPU_CTRL;
    gpu_ctrl__GPU_INTR_STATUS_t GPU_INTR_STATUS;
    gpu_ctrl__GPU_INTR_CLEAR_t GPU_INTR_CLEAR;
    gpu_ctrl__GPU_FE_MEM_OFFSET_t GPU_FE_MEM_OFFSET;
    gpu_ctrl__GPU_BE_MEM_OFFSET_t GPU_BE_MEM_OFFSET;
} gpu_ctrl_t;



#ifdef __cplusplus
}
#endif

#endif /* GPU_REGS_H */
