// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef VGA_CONTROLLER_H
#define VGA_CONTROLLER_H

#ifdef __cplusplus
extern "C" {
#endif

#include <linux/types.h>

// Reg - vga_ctrl::FRONT_BUF
#define VGA_CTRL__FRONT_BUF__BUF_ADDR_bm 0xffffffff
#define VGA_CTRL__FRONT_BUF__BUF_ADDR_bp 0
#define VGA_CTRL__FRONT_BUF__BUF_ADDR_bw 32
#define VGA_CTRL__FRONT_BUF__BUF_ADDR_reset 0xc8000000
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t BUF_ADDR :32;
    } f;
    uint32_t w;
} vga_ctrl__FRONT_BUF_t;

// Reg - vga_ctrl::BACK_BUF
#define VGA_CTRL__BACK_BUF__BACK_BUF_bm 0xffffffff
#define VGA_CTRL__BACK_BUF__BACK_BUF_bp 0
#define VGA_CTRL__BACK_BUF__BACK_BUF_bw 32
#define VGA_CTRL__BACK_BUF__BACK_BUF_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t BACK_BUF :32;
    } f;
    uint32_t w;
} vga_ctrl__BACK_BUF_t;

// Reg - vga_ctrl::RESOLUTION
#define VGA_CTRL__RESOLUTION__X_bm 0xffff
#define VGA_CTRL__RESOLUTION__X_bp 0
#define VGA_CTRL__RESOLUTION__X_bw 16
#define VGA_CTRL__RESOLUTION__X_reset 0x0
#define VGA_CTRL__RESOLUTION__Y_bm 0xffff0000
#define VGA_CTRL__RESOLUTION__Y_bp 16
#define VGA_CTRL__RESOLUTION__Y_bw 16
#define VGA_CTRL__RESOLUTION__Y_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t X :16;
        uint32_t Y :16;
    } f;
    uint32_t w;
} vga_ctrl__RESOLUTION_t;

// Reg - vga_ctrl::STAT_CTRL
#define VGA_CTRL__STAT_CTRL__S_bm 0x1
#define VGA_CTRL__STAT_CTRL__S_bp 0
#define VGA_CTRL__STAT_CTRL__S_bw 1
#define VGA_CTRL__STAT_CTRL__S_reset 0x0
#define VGA_CTRL__STAT_CTRL__A_bm 0x2
#define VGA_CTRL__STAT_CTRL__A_bp 1
#define VGA_CTRL__STAT_CTRL__A_bw 1
#define VGA_CTRL__STAT_CTRL__A_reset 0x0
#define VGA_CTRL__STAT_CTRL__EN_bm 0x4
#define VGA_CTRL__STAT_CTRL__EN_bp 2
#define VGA_CTRL__STAT_CTRL__EN_bw 1
#define VGA_CTRL__STAT_CTRL__EN_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t S :1;
        uint32_t A :1;
        uint32_t EN :1;
        uint32_t :29;
    } f;
    uint32_t w;
} vga_ctrl__STAT_CTRL_t;

// Addrmap - vga_ctrl
typedef struct __attribute__ ((__packed__)) {
    vga_ctrl__FRONT_BUF_t FRONT_BUF;
    vga_ctrl__BACK_BUF_t BACK_BUF;
    vga_ctrl__RESOLUTION_t RESOLUTION;
    vga_ctrl__STAT_CTRL_t STAT_CTRL;
} vga_ctrl_t;



#ifdef __cplusplus
}
#endif

#endif /* VGA_CONTROLLER_H */
