`ifndef TC_VN_SHADE_PER_VERTEX_SV
`define TC_VN_SHADE_PER_VERTEX_SV
`timescale 1ps/1ps

import uvm_pkg::*;
import pipe_pkg::*;
import vn_shade_env_pkg::*;
import vn_shade_seq_pkg::*;
import cmodel_query_pkg::*;

`include "uvm_macros.svh"

// Directed per-vertex dot-product test, golden-driven by the cmodel_golden
// shared library (ABI v2).
//
// Both frames drive the box light and directed streams of DISTINCT vertex
// normals, and every expected vn_o is generated at runtime from the C
// model's exact-shade reference (cmodel_shade_dot_exact: exact 3-term sum,
// one arithmetic floor shift — the DUT's intended datapath arithmetic). No
// hardcoded expected-value tables.
//
// Frame 1: 8 directed normals, each distinct from its neighbors so that both
// a light-component desync (a normal component paired with the wrong light
// component) and a stream shift (spurious leading 0, so output n is scored
// against vertex n+1) surface as ordered scoreboard mismatches. The
// scoreboard compares outputs strictly in order against the expected queue
// and has no skip/absorb logic, so the FIRST output must equal the FIRST
// vertex's N.L (-10711 under the box light, not 0) — a spurious leading 0
// is a mismatch, never absorbed.
//
// Frame 2: the 36-vertex box normal stream read from the C model's loaded
// copy of tests/testcases/memh/box.memh (cmodel_get_vertex_raw) — stimulus
// generated by the reference, not hardcoded — with the box light. The
// per-vertex C-model exact-shade goldens for this mesh equal
// tests/testcases/memh/shade.memh under that light.
//
// The env scoreboard scores in external-golden mode (ext_golden_mode):
// each expected value is pushed by this test from the C model, and the
// scoreboard cross-checks it against its own inline Q13.14 computation —
// a disagreement between the two references is a UVM_ERROR in its own
// right.

class tc_vn_shade_per_vertex extends vn_shade_base_test;
  `uvm_component_utils(tc_vn_shade_per_vertex)

  // Box light (Q13.14; 1.0 = 16384) — words 16-18 of tests/testcases/memh/box.memh.
  localparam logic signed [26:0] BOX_LX =  27'sd10711;
  localparam logic signed [26:0] BOX_LY = -27'sd10081;
  localparam logic signed [26:0] BOX_LZ =  27'sd7217;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  // Push the C-model golden for one directed normal, then drive it.
  task send_shaded_normal(logic signed [26:0] nx,
                          logic signed [26:0] ny,
                          logic signed [26:0] nz);
    int signed exp;
    exp = cmodel_shade_dot_exact(int'(BOX_LX), int'(BOX_LY), int'(BOX_LZ),
                                 int'(nx), int'(ny), int'(nz));
    env.scb.push_ext_exp(exp[26:0]);
    send_normal(nx, ny, nz);
  endtask

  task run_phase(uvm_phase phase);
    int nbox;
    phase.raise_objection(this);

    // -------------------------------------------------------------------
    // C-model golden setup: per-vertex goldens for BOTH frames come from
    // the exact-shade reference; frame-2 normal stimulus comes from the
    // loaded box mesh. No hardcoded expected-value tables.
    // -------------------------------------------------------------------
    if (!cmodel_version_ok())
      `uvm_fatal("CMODEL_ABI", $sformatf("cmodel_version() = %0d, expected 2 — rebuild libcmodel_golden.so against cmodel_golden.h", int'(cmodel_version())))
    if (gpu_cmodel_pkg::cmodel_load_mesh("memh/box.memh") != gpu_cmodel_pkg::CMODEL_OK)
      `uvm_fatal("CMODEL_LOAD", "cmodel_load_mesh(\"memh/box.memh\") failed — check the sim CWD (the flow symlinks tests/testcases/memh as ./memh in the run dir)")
    nbox = cmodel_vertex_count();
    if (nbox != 36)
      `uvm_fatal("CMODEL_MESH", $sformatf("box.memh: cmodel_vertex_count() = %0d, expected 36", nbox))
    env.scb.ext_golden_mode = 1;

    // -------------------------------------------------------------------
    // Frame 1: box light + 8 directed normals (distinct, in order)
    // -------------------------------------------------------------------
    wait_for_reset();

    `uvm_info("TC", $sformatf("Frame 1: box light (Lx=%0d, Ly=%0d, Lz=%0d) + 8 directed normals", BOX_LX, BOX_LY, BOX_LZ), UVM_LOW)

    // Light preamble (Q13.14). All three components non-zero so a
    // light-component desync is observable.
    send_light(BOX_LX, BOX_LY, BOX_LZ);

    // Directed normals (Q13.14), each distinct from its neighbors:
    //   (nx, ny, nz)          expected N.L (box light)
    //   (-1,  0,  0)          -10711
    //   ( 0,  0, -1)          -7217
    //   ( 0, +1,  0)          -10081
    //   ( 0,  0, +1)           7217
    //   ( 0, -1,  0)          +10081
    //   (+1,  0,  0)          +10711
    //   (+1/2, +1/2, +1/2)     3923
    //   (-1/2,  0, +1/2)      -1747
    // Goldens: cmodel_shade_dot_exact under the box light (the first
    // output must be -10711, not 0).
    send_shaded_normal(-27'sd16384, 27'sd0,       27'sd0);
    send_shaded_normal( 27'sd0,     27'sd0,     -27'sd16384);
    send_shaded_normal( 27'sd0,      27'sd16384, 27'sd0);
    send_shaded_normal( 27'sd0,      27'sd0,      27'sd16384);
    send_shaded_normal( 27'sd0,     -27'sd16384,  27'sd0);
    send_shaded_normal( 27'sd16384,  27'sd0,      27'sd0);
    send_shaded_normal( 27'sd8192,   27'sd8192,   27'sd8192);
    send_shaded_normal(-27'sd8192,   27'sd0,      27'sd8192);

    // Drain the DUT's output pipeline before the frame-boundary reset.
    wait_drained();

    // -------------------------------------------------------------------
    // Frame 2: box light + 36-vertex box normal stream from the C model's
    // loaded mesh (stimulus from the reference, not hardcoded)
    // -------------------------------------------------------------------
    new_frame();

    `uvm_info("TC", $sformatf("Frame 2: box light (Lx=%0d, Ly=%0d, Lz=%0d) + %0d-vertex box normal stream from box.memh", BOX_LX, BOX_LY, BOX_LZ, nbox), UVM_LOW)

    send_light(BOX_LX, BOX_LY, BOX_LZ);

    for (int i = 0; i < nbox; i++) begin
      int pos[4];
      int nrm[3];
      if (cmodel_get_vertex_raw(i, pos, nrm) != CMODEL_OK)
        `uvm_fatal("CMODEL_VTX", $sformatf("cmodel_get_vertex_raw(%0d) failed", i))
      send_shaded_normal(nrm[0][26:0], nrm[1][26:0], nrm[2][26:0]);
    end

    wait_drained();

    #500ns;
    `uvm_info("TC", "Finished tc_vn_shade_per_vertex transactions.", UVM_LOW)
    phase.drop_objection(this);
  endtask

endclass

`endif
