`ifndef TC_VERTEX_PROCESSOR_CMODEL_SV
`define TC_VERTEX_PROCESSOR_CMODEL_SV
`timescale 1ps/1ps

import uvm_pkg::*;
import pipe_pkg::*;
import clk_rst_pkg::*;
import vertex_processor_env_pkg::*;
import vertex_processor_seq_pkg::*;
import cmodel_query_pkg::*;

`include "uvm_macros.svh"

// Per-vertex cmodel-golden subsystem test (box.memh, 36 vertices).
//
// Stimulus: the frame is built from the C model's loaded copy of
// tests/testcases/memh/box.memh - the 16 matrix words from
// cmodel_get_matrix, the box light (mesh words 16-18), the count word
// from cmodel_vertex_count, and the per-vertex position/normal words
// from cmodel_get_vertex_raw (stimulus generated by the reference, not
// hardcoded).
//
// Expected values: per-vertex goldens from the v3 stage-oracle chain
// (cmodel_vertex_xform_exact -> cmodel_w_norm_exact) for the pos channel
// plus cmodel_shade_dot_exact on the raw normals for the shade channel.
// The scoreboard scores against the pushed goldens (ext_golden_mode) and
// cross-checks its own inline model against them - a disagreement between
// the two references is a UVM_ERROR in its own right.
//
// Two identical frames: frame 2 exercises the per-frame light re-send
// path (the DUT must re-latch the light rather than consume those words
// as normal components).
//
// Post-run cross-check: cmodel_get_vertex_xform (the cmodel's own
// per-term-rounded fpm::fixed transform, only valid against the DUT for
// w==1 affine matrices such as the box) must agree with the 1a+1b
// chain golden within 2 LSB per component.

class tc_vertex_processor_cmodel extends vertex_processor_base_test;
  `uvm_component_utils(tc_vertex_processor_cmodel)

  // Box light (Q13.14; 1.0 = 16384) - words 16-18 of tests/testcases/memh/box.memh.
  localparam int BOX_LX =  10711;
  localparam int BOX_LY = -10081;
  localparam int BOX_LZ =  7217;

  // Per-term-rounding tolerance for the cmodel_get_vertex_xform cross-check.
  // 1a/1b are pure functions of (matrix, pos) — the DUT must match bit-exactly.
  // Tolerance 32 = 2^-14 * 2^18 only admits the 18th-bit truncation-vs-rounding
  // difference of the LPM divider (the C self-test tolerates 31); anything
  // larger is a DUT defect.
  localparam int XCHK_TOL = 32;

  int mat[16];
  int vtx_words[$];
  int xg[36][4]; // 1a+1b golden pos (x,y,z,w) per vertex, for the xform cross-check

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  // Build the frame stimulus (mat, vtx_words) and the 1a+1b pos goldens.
  protected task build_frame();
    int n, i, c;
    int pos[4];
    int nrm[3];
    int xo[4];
    int po[4];

    n = cmodel_vertex_count();
    if (n != 36)
      `uvm_fatal("CMODEL_MESH", $sformatf("box.memh: cmodel_vertex_count() = %0d, expected 36", n))
    if (cmodel_get_matrix(mat) != CMODEL_OK)
      `uvm_fatal("CMODEL_MATRIX", "cmodel_get_matrix failed (mesh not loaded?)")

    vtx_words.delete();
    for (i = 0; i < n; i++) begin
      if (cmodel_get_vertex_raw(i, pos, nrm) != CMODEL_OK)
        `uvm_fatal("CMODEL_VTX", $sformatf("cmodel_get_vertex_raw(%0d) failed", i))
      for (c = 0; c < 4; c++) vtx_words.push_back(pos[c]);
      for (c = 0; c < 3; c++) vtx_words.push_back(nrm[c]);

      if (cmodel_vertex_xform_exact(mat, pos, xo) != CMODEL_OK)
        `uvm_fatal("CMODEL_XFORM", $sformatf("cmodel_vertex_xform_exact(%0d) failed", i))
      if (cmodel_w_norm_exact(xo[0], xo[1], xo[2], xo[3], po) != CMODEL_OK)
        `uvm_fatal("CMODEL_WNORM", $sformatf("cmodel_w_norm_exact(%0d) failed", i))
      for (c = 0; c < 4; c++) xg[i][c] = po[c];
    end
  endtask

  // Push one cmodel golden per vertex (vertex order): the 1a+1b pos
  // golden plus the exact-shade dot on the raw normal.
  protected task push_goldens();
    int n, i;
    int raw_pos[4];
    int nrm[3];
    int shade;

    n = cmodel_vertex_count();
    for (i = 0; i < n; i++) begin
      if (cmodel_get_vertex_raw(i, raw_pos, nrm) != CMODEL_OK)
        `uvm_fatal("CMODEL_VTX", $sformatf("cmodel_get_vertex_raw(%0d) failed", i))
      shade = cmodel_shade_dot_exact(BOX_LX, BOX_LY, BOX_LZ, nrm[0], nrm[1], nrm[2]);
      env.scb.push_ext_golden(xg[i][0], xg[i][1], xg[i][2], xg[i][3], shade);
    end
  endtask

  // The cmodel's own rendered transform must match the 1a+1b chain
  // within the per-term-rounding tolerance (valid for w==1 affine data).
  protected task xform_cross_check();
    int n, i, c, diff;
    int xc[4];

    n = cmodel_vertex_count();
    for (i = 0; i < n; i++) begin
      if (cmodel_get_vertex_xform(i, xc) != CMODEL_OK) begin
        `uvm_error("XCHK", $sformatf("cmodel_get_vertex_xform(%0d) failed (cmodel_render did not run?)", i))
      end else begin
        for (c = 0; c < 4; c++) begin
          diff = xc[c] - xg[i][c];
          if (diff < 0) diff = -diff;
          if (diff > XCHK_TOL)
            `uvm_error("XCHK", $sformatf("vertex %0d component %0d: cmodel_get_vertex_xform = %0d, 1a+1b golden = %0d (diff %0d > %0d)", i, c, xc[c], xg[i][c], diff, XCHK_TOL))
        end
      end
    end
  endtask

  task run_phase(uvm_phase phase);
    int light[3];
    string mesh_path;

    phase.raise_objection(this);

    // -------------------------------------------------------------------
    // C-model setup
    // -------------------------------------------------------------------
    if (!cmodel_version_ok())
      `uvm_fatal("CMODEL_ABI", $sformatf("cmodel_version() = %0d, expected 3 - rebuild libcmodel_golden.so against cmodel_golden.h (ABI v3)", int'(cmodel_version())))
    // Shared resolver (gpu_cmodel_pkg::get_mesh_file): +MEMH/+MEMH_DIR
    // plusargs, falling back to CWD-relative ./memh/box.memh (the single-run
    // flow symlinks tests/testcases/memh as ./memh in the run dir). The
    // vmanager regression has no ./memh symlink in its session dir, so
    // regression.vsif passes +MEMH='$ENV(MEMH_DIR)/box.memh' for this test.
    mesh_path = gpu_cmodel_pkg::get_mesh_file();
    if (gpu_cmodel_pkg::cmodel_run(mesh_path) != gpu_cmodel_pkg::CMODEL_OK)
      `uvm_fatal("CMODEL_RUN", $sformatf("cmodel_run(\"%s\") failed - check the +MEMH plusarg (vmanager regression) or the run dir ./memh symlink (single-run flow)", mesh_path))

    build_frame();
    env.scb.ext_golden_mode = 1;

    wait_for_reset();

    // -------------------------------------------------------------------
    // Frame 1: box matrix + light + 36 box vertices
    // -------------------------------------------------------------------
    light = '{BOX_LX, BOX_LY, BOX_LZ};
    `uvm_info("TC", $sformatf("Frame 1: box matrix + light (%0d, %0d, %0d) + %0d box vertices", BOX_LX, BOX_LY, BOX_LZ, cmodel_vertex_count()), UVM_LOW)
    env.scb.reset_state();
    push_goldens();
    send_frame(mat, light, vtx_words);

    // -------------------------------------------------------------------
    // Frame 2: identical box frame (per-frame light re-send path)
    // -------------------------------------------------------------------
    `uvm_info("TC", "Frame 2: identical box frame (light re-send path)", UVM_LOW)
    env.scb.reset_state();
    push_goldens();
    send_frame(mat, light, vtx_words);

    // -------------------------------------------------------------------
    // w==1 xform cross-check (cmodel render vs 1a+1b chain)
    // -------------------------------------------------------------------
    xform_cross_check();

    #500ns;
    `uvm_info("TC", "Finished tc_vertex_processor_cmodel transactions.", UVM_LOW)
    phase.drop_objection(this);
  endtask

endclass

`endif
