$PROJ_DIR/tests/testcases/tc_axfe_basic_wr_rd.sv
$PROJ_DIR/tests/testcases/tc_axfe_regmap_corner.sv
$PROJ_DIR/tests/testcases/tc_axfe_start_done.sv
$PROJ_DIR/tests/testcases/tc_axfe_start_busy.sv
$PROJ_DIR/tests/testcases/tc_axfe_start_dma_overlap.sv
$PROJ_DIR/tests/testcases/tc_axfe_dma_backpressure.sv
$PROJ_DIR/tests/testcases/tc_axfe_dma_base_offset.sv
$PROJ_DIR/tests/testcases/tc_axfe_dma_timeout.sv
$PROJ_DIR/tests/testcases/tc_axfe_reset_behavior.sv
$PROJ_DIR/tests/testcases/tc_axfe_intr_status_lifecycle.sv
$PROJ_DIR/tests/testcases/tc_axfe_bus_timing.sv
$PROJ_DIR/tests/testcases/tc_axfe_resp_status.sv
$PROJ_DIR/tests/testcases/tc_axfe_wait_block_write.sv
$PROJ_DIR/tests/testcases/tc_axfe_reset_mid_write.sv
$PROJ_DIR/tests/testcases/tc_axfe_reset_mid_read.sv
$PROJ_DIR/tests/testcases/tc_axfe_reset_mid_dma.sv
$PROJ_DIR/tests/testcases/tc_axfe_reset_mid_start.sv
$PROJ_DIR/tests/testcases/tc_axfe_wstrb_partial.sv
$PROJ_DIR/tests/testcases/tc_axfe_prot_variety.sv
$PROJ_DIR/tests/testcases/tc_rop_basic.sv
$PROJ_DIR/tests/testcases/tc_rop_backend_basic.sv
$PROJ_DIR/tests/testcases/tc_gpu_smoke_wr_rd.sv
$PROJ_DIR/tests/testcases/tc_gpu_sys_access_basic.sv
$PROJ_DIR/tests/testcases/tc_gpu_multi_frame.sv
$PROJ_DIR/tests/testcases/tc_gpu_render_golden.sv
#$PROJ_DIR/tests/testcases/tc_axilfe_error/tc_axilfe_error.sv
#$PROJ_DIR/tests/testcases/tc_axil_sys_access/tc_axil_sys_access.sv
#$PROJ_DIR/tests/testcases/tc_axil_slave/tc_axil_slave.sv
#$PROJ_DIR/tests/testcases/tc_multiple_frames/tc_multiple_frames.sv
